language: node_js
node_js:
  - stable

cache:
  yarn: true

script: yarn test

before_deploy: yarn deploy
deploy:
  provider: npm
  email: dustinschau@gmail.com
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
